import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.dsl.abi.ExperimentalAbiValidation

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    alias(libs.plugins.android.kmp.library)
    alias(libs.plugins.vanniktech.publish)
    alias(libs.plugins.dokka)
}

/*
 * The :kitecore module builds the KiteCore runtime library.
 *
 * v0.1.0 provides:
 *   - ioDispatcher(): a unified IO CoroutineDispatcher. Dispatchers.IO on
 *     JVM, Android, and Apple (public on Native since coroutines 1.7), and
 *     an installed dispatcher or Dispatchers.Default on the web targets.
 *   - KiteWorker (js and wasmJs): an inline Blob Web Worker offload
 *     primitive using protocol v2 (correlation ids).
 *   - Platform.current: name, osVersion, deviceModel, and family per target.
 *
 * The only dependency is kotlinx-coroutines-core, exposed via `api` because
 * ioDispatcher() returns a CoroutineDispatcher.
 */

// KiteCore.VERSION is generated from the Gradle project version, which comes
// from gradle.properties.
val generateKiteCoreVersion by tasks.registering {
    val version = project.version.toString()
    val outDir = layout.buildDirectory.dir("generated/kitecore/commonMain/kotlin")
    inputs.property("version", version)
    outputs.dir(outDir)
    doLast {
        val file = outDir.get().file("io/github/yuroyami/kitecore/KiteCore.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            |/* Generated by generateKiteCoreVersion. Do not edit. */
            |package io.github.yuroyami.kitecore
            |
            |/** KiteCore library metadata. */
            |public object KiteCore {
            |    /** The KiteCore version, injected from the Gradle project version at build time. */
            |    public const val VERSION: String = "$version"
            |}
            |
            """.trimMargin()
        )
    }
}

kotlin {
    explicitApi()

    // KiteWeak is an expect/actual class, which is Beta in Kotlin 2.4 and
    // requires -Xexpect-actual-classes.
    compilerOptions {
        freeCompilerArgs.add("-Xexpect-actual-classes")
    }

    jvmToolchain(21)

    android {
        namespace = "io.github.yuroyami.kitecore"
        compileSdk = 36
        minSdk = 21
        withHostTestBuilder {}
    }

    // Compile with the JDK 21 toolchain but target JVM 11 bytecode so the
    // published library runs on JDK 11 and later.
    jvm {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_11)
            freeCompilerArgs.add("-Xjdk-release=11")
        }
    }

    // Apple targets. Maven consumers compile against klibs; no framework
    // binaries are produced here. macosX64 is omitted because it is
    // deprecated for removal in Kotlin 2.4.
    // See https://kotl.in/native-targets-tiers.
    iosArm64()
    iosSimulatorArm64()
    iosX64()
    macosArm64()

    // Web
    js {
        browser()
        nodejs()
        binaries.library()
    }
    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        browser()
        nodejs()
    }

    // Invoking abiValidation {} enables ABI validation in Kotlin 2.4; the
    // former `enabled` property was removed.
    @OptIn(ExperimentalAbiValidation::class)
    abiValidation {
    }

    sourceSets {
        commonMain {
            kotlin.srcDir(generateKiteCoreVersion)
            dependencies {
                api(libs.kotlinx.coroutines.core)
            }
        }

        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation(libs.kotlinx.coroutines.test)
        }
    }
}

// The ABI dump under kitecore/api/ is the recorded public surface. `check`
// fails when the code drifts from it. Regenerate it with
// `./gradlew :kitecore:updateKotlinAbi`.
tasks.named("check") {
    dependsOn("checkKotlinAbi")
}

// Publishing is configured by the vanniktech plugin from gradle.properties:
// shared coordinates/POM/signing in the root gradle.properties, this module's
// POM_NAME + POM_DESCRIPTION in kitecore/gradle.properties.

